version: '3'

services:
  API:
    container_name: node_container
    image: node
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - mongodb
    environment:
      PORT: 3005
      MONGO_URI: mongodb://mongodb:27017/Notifications
    ports:
      - 3005:3005

  mongodb:
    image: mongo:4.0
    container_name: mongoDB
    volumes:
      - ./:/app
    restart: always
    ports:
      - 27017:27017

networks:
  default:
    name: notification_net