version: '3'

services:
  API:
    container_name: node_container
    image: node
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      PORT: 3005
    ports:
      - 3005:3005